#!/bin/bash
date  >> /tmp/competitor_monotaro.txt
DB_GCP='price_check';
DB_TORA='toranote_real';

HOST_GPC='xxxx.rds.amazonaws.com';
USER_GPC='xxxx';
PASS_GPC='xxxx';

HOST_TORA='yyyy.rds.amazonaws.com';
USER_TORA='figo_jp';
PASS_TORA='yyyy';

mysql -h $HOST_GPC -u $USER_GPC --password=$PASS_GPC -D $DB_GCP --execute='SET NAMES utf8;SELECT product_code,review_count,up_date FROM competitor_monotaro WHERE product_code is not null and  up_date > NOW() - INTERVAL 1 MONTH' | sed ':a; s/\(^\|\t\)NULL\(\t\|$\)/\1\\N\2/; t a' > /tmp/competitor_monotaro.csv;
mysql -h $HOST_TORA -u $USER_TORA --password=$PASS_TORA -D $DB_TORA --execute='LOAD DATA LOCAL INFILE "/tmp/competitor_monotaro.csv" REPLACE INTO TABLE competitor_monotaro CHARACTER SET "utf8" IGNORE 1 LINES';

date  >> /tmp/competitor_monotaro.txt
